/** Route-level API inventory; Zod validators remain the executable field contract. */
const operation = (summary: string, security?: 'user' | 'admin' | 'any', successCode = '200') => ({
  summary,
  ...(security ? {
    security: security === 'any'
      ? [{ userBearerAuth: [] }, { adminBearerAuth: [] }]
      : [{ [security === 'user' ? 'userBearerAuth' : 'adminBearerAuth']: [] }],
  } : {}),
  responses: { [successCode]: { description: 'Successful response' }, '401': { description: 'Authentication is required or invalid' }, '422': { description: 'Validation failed' } },
});

export const openapi: Record<string, unknown> = {
  openapi: '3.0.3',
  info: { title: 'ElectroMart API', version: '1.0.0', description: '`/api` is the compatible prefix; `/api/v1` is its versioned equivalent.' },
  servers: [{ url: '/api', description: 'Compatible API prefix' }, { url: '/api/v1', description: 'Versioned API prefix' }],
  components: {
    securitySchemes: {
      userBearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'User JWT' },
      adminBearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'Admin JWT' },
    },
    schemas: {
      Success: { type: 'object', required: ['success', 'message', 'data'], properties: { success: { type: 'boolean', example: true }, message: { type: 'string' }, data: {} } },
      Error: { type: 'object', required: ['success', 'code', 'message'], properties: { success: { type: 'boolean', example: false }, code: { type: 'string' }, message: { type: 'string' }, requestId: {} } },
    },
  },
  paths: {
    '/health': { get: operation('Liveness health check') },
    '/ready': { get: operation('Readiness check, including MongoDB connectivity') },
    '/auth/signup': { post: operation('Create an unverified customer account', undefined, '201') },
    '/auth/send-otp': { post: operation('Send a signup, login, or reset OTP') },
    '/auth/verify-otp': { post: operation('Verify signup, reset, or login OTP') },
    '/auth/login': { post: operation('Verify customer password and begin OTP login') },
    '/auth/verify-login-otp': { post: operation('Complete OTP login and set refresh cookie') },
    '/auth/forgot-password': { post: operation('Request password reset without revealing account state') },
    '/auth/reset-password': { post: operation('Set password after reset OTP verification') },
    '/auth/refresh-token': { post: operation('Rotate customer refresh session') },
    '/auth/logout': { post: operation('Invalidate customer refresh session', 'user') },
    '/auth/me': { get: operation('Get current customer profile', 'user') },
    '/auth/change-password': { post: operation('Change password and invalidate sessions', 'user') },
    '/admin/auth/login': { post: operation('Administrator sign-in') },
    '/admin/auth/create-sub-admin': { post: operation('Create sub-administrator (primary administrator only)', 'admin', '201') },
    '/admin/auth/refresh-token': { post: operation('Rotate administrator refresh session') },
    '/admin/auth/logout': { post: operation('Invalidate administrator refresh session', 'admin') },
    '/admin/auth/me': { get: operation('Get current administrator profile', 'admin') },
    '/categories': { get: operation('Get nested category tree'), post: operation('Create category or subcategory', 'admin', '201') },
    '/categories/{slug}': { get: operation('Get category, immediate children, and product count') },
    '/categories/{id}': { put: operation('Update category', 'admin'), delete: operation('Delete unused category', 'admin') },
    '/products': { get: operation('List, search, filter, and page active products'), post: operation('Create multipart product', 'admin', '201') },
    '/products/{slug}': { get: operation('Get product detail') },
    '/products/{slug}/related': { get: operation('Get related products') },
    '/products/{id}': { put: operation('Update multipart product', 'admin'), delete: operation('Archive product', 'admin') },
    '/products/{id}/stock': { patch: operation('Atomically adjust product stock', 'admin') },
    '/products/{id}/status': { patch: operation('Set product lifecycle status', 'admin') },
    '/products/{id}/images': { post: operation('Add or replace product images', 'admin') },
    '/products/{id}/inventory-history': { get: operation('Get product inventory movements', 'admin') },
    '/cart': { get: operation('Get cart with live price and availability checks', 'user') },
    '/cart/add': { post: operation('Add or increment cart item', 'user') },
    '/cart/update': { put: operation('Set cart item quantity', 'user') },
    '/cart/remove/{productId}': { delete: operation('Remove cart item', 'user') },
    '/cart/clear': { delete: operation('Clear cart', 'user') },
    '/orders': { post: operation('Place COD order', 'user', '201'), get: operation('List all orders for administration', 'admin') },
    '/orders/my-orders': { get: operation('List current customer orders', 'user') },
    '/orders/my-orders/{id}': { get: operation('Get current customer order', 'user') },
    '/orders/my-orders/{id}/cancel': { patch: operation('Cancel placed customer order', 'user') },
    '/orders/{id}': { get: operation('Get order detail', 'admin') },
    '/orders/{id}/status': { patch: operation('Advance order fulfilment state', 'admin') },
    '/reviews/product/{productId}': { get: operation('List approved product reviews'), post: operation('Create customer review', 'user', '201') },
    '/reviews/{id}': { put: operation('Edit own review', 'user'), delete: operation('Delete own review or moderate as administrator', 'any') },
    '/reviews/{id}/moderate': { patch: operation('Set review approval state', 'admin') },
    '/coupons/apply': { post: operation('Preview coupon discount against current cart', 'user') },
    '/coupons': { get: operation('List coupons', 'admin'), post: operation('Create coupon', 'admin', '201') },
    '/coupons/{id}': { put: operation('Update coupon', 'admin'), delete: operation('Deactivate coupon', 'admin') },
    '/wishlist': { get: operation('Get customer wishlist', 'user') },
    '/wishlist/add/{productId}': { post: operation('Add active product to wishlist', 'user') },
    '/wishlist/remove/{productId}': { delete: operation('Remove wishlist product', 'user') },
    '/addresses': { get: operation('List saved addresses', 'user'), post: operation('Add address', 'user', '201') },
    '/addresses/{id}': { put: operation('Update saved address', 'user'), delete: operation('Delete saved address', 'user') },
    '/addresses/{id}/set-default': { patch: operation('Set default saved address', 'user') },
    '/admin/dashboard/stats': { get: operation('Get administration dashboard totals', 'admin') },
    '/admin/dashboard/revenue-chart': { get: operation('Get delivered-revenue chart', 'admin') },
    '/admin/dashboard/top-products': { get: operation('Get best-selling products', 'admin') },
    '/admin/dashboard/low-stock': { get: operation('Get low-stock products', 'admin') },
    '/admin/dashboard/recent-orders': { get: operation('Get recent orders', 'admin') },
    '/admin/users': { get: operation('Search and page customers', 'admin') },
    '/admin/users/{id}/status': { patch: operation('Activate or deactivate customer and revoke refresh sessions', 'admin') },
  },
};
